# golangci-lint configuration
version: 2

run:
  # Timeout for analysis
  timeout: 5m
  
  # Tests are disabled (skip *_test.go files)
  tests: false
  
  # Skip directories
  skip-dirs:
    - testdata
    - tests

linters:
  # Only enable default linters (without unused which flags test utilities)
  enable:
    - errcheck
    - staticcheck
    - ineffassign
    - govet
  
  # Disable unused as it flags legitimate test utility functions
  disable:
    - unused

linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions
    check-type-assertions: true
    # Report about assignment of errors to blank identifier
    check-blank: true
  
  staticcheck:
    # Use the default checks
    checks: ["all"]
  
  govet:
    # Report about shadowed variables
    check-shadowing: true

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text
  max-same-issues: 3