# golangci-lint configuration for JFrog CLI Evidence

run:
  # Timeout for analysis
  timeout: 5m
  
  # Include test files
  tests: true
  
  # Skip directories
  skip-dirs:
    - vendor
    - mocks
    - testdata
    
  # Skip files
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - prealloc
    - predeclared
    - asciicheck
    - errorlint
    - exhaustivestruct
    - exportloopref
    - gochecknoglobals
    - gocognit
    - godot
    - godox
    - goerr113
    - gofumpt
    - goheader
    - gomodguard
    - makezero
    - nestif
    - nlreturn
    - nolintlint
    - paralleltest
    - thelper
    - tparallel
    - testpackage
    - wrapcheck
    - wsl

  disable:
    - maligned
    - funlen
    
linters-settings:
  dupl:
    threshold: 100
    
  exhaustive:
    default-signifies-exhaustive: false
    
  gocyclo:
    min-complexity: 15
    
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
        
  govet:
    check-shadowing: true
    
  lll:
    line-length: 140
    
  misspell:
    locale: US
    
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
    
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      
  errorlint:
    errorf: true
    
  goimports:
    local-prefixes: github.com/jfrog/jfrog-cli-evidence
    
  gosec:
    excludes:
      - G104  # Unhandled errors in defer statements
      - G204  # Subprocess launched with variable
      - G304  # File path provided as taint input
      
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gomnd
        
    # Exclude known linters from partially hard-vendored code
    - path: pkg/mod/
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gomnd
        
    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
      
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text
  max-same-issues: 0
  
  # Show only new issues
  new: false
